server:
  ip: 0.0.0.0
  port: 38062
spring:
  cloud:
    config:
      server:
        git:
          #这是其他项目配置文件的git仓库地址
#          uri: https://git.coding.net/yirenyishi/springcloud-config-profile
#          searchPaths: '{application}'
          uri: https://github.com/andypeker/springcloud-frankie1.git
          searchPaths: config-info
          default-label: master
          username: root
          password: password
    client:
      ipAddress: ${server.ip}
eureka:
  instance:
    appname: springcloud-config-server
    hostname: ${global.eureka-ip}
    port: ${global.eureka-port}
    prefer-ip-address: true
    #可能比较长，复制的时候请写在一行
#    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
#    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      #注册服务到eureka上，记住这里要加上eureka-server的用户名和密码
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
security:
  basic:
    enabled: true
  user:
    #这是config-server的用户名和密码
    name: root
    password: password

# spring.application.name 优先级 高于 eureka.instance.appname